"""Domain tool modules – imported to register tools on the shared ``mcp`` instance."""

from . import (  # noqa: F401
    connection,
    immobilien,
    contacts,
    activities,
    activity_templates,
    custom_fields,
    deals,
    tickets,
    documents,
    loans,
    milestones,
    units,
    tags,
    organisation,
    feed,
    email_messages,
    valuation,
    user,
    investor,
    pipelines,
    statuses,
)
